server:
  port: 1221
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.study.pojo